org: thrishma
app: world-holidays
service: world-holidays

frameworkVersion: '2 || 3'

plugins:
  - serverless-python-requirements

custom:
  bucket_name: slack-bot
  pythonRequirements:
    dockerizePip: non-linux
     

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  holidayFetcher:
    name: holiday_fetcher
    description: Web scrapes holidays from a given URL and saves it to s3
    handler: holiday_fetcher.handler
    timeout: 15
    environment:
      S3_BUCKET_NAME: ${self:custom.bucket_name}
      S3_FOLDER_NAME: holidays
    events:
      - schedule: rate(364 days)
  
  holidaySearcher:
    name: holiday_searcher
    description: Reads the file from s3 and returns the holidays in all over the world for a given date
    handler: holiday_searcher.handler
    timeout: 15
    environment:
      S3_BUCKET_NAME: ${self:custom.bucket_name}
      S3_FOLDER_NAME: holidays
      S3_FILE_NAME: list_of_holidays_per_date.json
    events:
      - schedule: rate(1 day)

